gerenciamento/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # Local
    path("", include("pages.urls", namespace="pages")),
    path("", include("pages.urls", namespace="storepage")),
    #path("", include("pessoa.urls", namespace="pagepessoa")),
    path("", include("pessoa.urls", namespace="form_modelform")),

]

pages/urls.py
from django.urls import path

from . import views


app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("store/", views.storepage, name="storepage"),
]

pessoa/urls.py
from django.urls import path
from .views import ListaPessoaView
from . import views


app_name = "pessoa"


urlpatterns = [
    #path("pessoa/", views.pagepessoa, name="pagepessoa"),
    path("pessoa/", views.form_modelform, name="form_modelform"),

]

pages/models.py
from django.db import models

# Create your models here.

pessoa/models.py
from django.db import models
from django.contrib.auth.models import User


class Pessoa(models.Model):
    nome_completo = models.CharField(max_length=256)
    data_nascimento = models.DateField(null=True)
    ativa = models.BooleanField(default=True)
    uf = models.CharField(max_length=2)

    def __str__(self):
        return self.uf

pessoa/forms.py
from django import forms

from pessoa.models import Pessoa


class PessoaForm(forms.ModelForm):
    class Meta:
        model = Pessoa
        fields = "__all__"

pages/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from pessoa.models import Pessoa
from django.db.models import Count


def storepage(request):

    data = Pessoa.objects.all().values('uf').annotate(total=Count('uf')).order_by('uf')


    return render(request, 'store.html', context={'data': data})


class HomePageView(TemplateView):
    template_name = "home.html"

pessoa/views.py
import json

from django.db.models import Count
from django.shortcuts import render
from django.views.generic import ListView
import conectdb

from .forms import PessoaForm
from pessoa.models import Pessoa


class ListaPessoaView(ListView):
    model = Pessoa
    queryset = Pessoa.objects.all().order_by('nome_completo')


# def pagepessoa(request):
#     return render(request, 'pessoa.html')


def form_modelform(request):
    if request.method == "GET":
        form = PessoaForm()
        context = {
            'form': form
        }
        return render(request, "pessoa.html", context=context)
    else:
        form = PessoaForm(request.POST)
        if form.is_valid():
            cliente = form.save()
            form = PessoaForm()
        context = {
            'form': form
        }
        return render(request, "pessoa.html", context=context)


def clientes(request):
    data = {Pessoa.objects.all().values('us').annotate(total=Count('uf')).order_by('-total')}
    return render(request, "home.html", context={'data': data})

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Sistema de Gerenciamento</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Sistema de Gerenciamento{% endblock %}

{% block content %}
    Bem-vindo!
{% endblock %}

templates/pessoa.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sistema de Gerenciamento{% endblock %}

{% block content %}
    cadastro de pessoas
<body>
<form action="." method="post">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Salvar">
</form>
</body>

{% endblock %}


</div>
<div class="container-fluid">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active" href="/pessoa">Novo cadastro</a>
        </li>
    </ul>
</div>

templates/store.html
{% extends 'base.html' %}
{% block title %}Sistema de Gerenciamento{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="#" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
                        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="/pessoa" class="nav-link px-0"> <span class="d-none d-sm-inline">cadastro</span>  </a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
                    </li>
                    <li>
                        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>
                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
                            <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>
                    </li>
                </ul>
                <hr>
                <div class="dropdown pb-4">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="" alt="hugenerd" width="30" height="30" class="rounded-circle">
                        <span class="d-none d-sm-inline mx-1">loser</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                        <li><a class="dropdown-item" href="#">New project...</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col py-3">
            <html>
              <head>
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                <script type="text/javascript">
                  google.charts.load("current", {packages:["corechart"]});
                  google.charts.setOnLoadCallback(drawChart);
                  function drawChart() {
                    var data = google.visualization.arrayToDataTable([
                    ['estado', 'quantidade'],
                    {% for estado in data %}
                      ['{{ estado.uf }}', {{ estado.total }}],
                    {% endfor %}

                    ]);
                    var options = {
                      title: 'Clientes por estado',
                      pieHole: 0.4,
                    };

                    var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
                    chart.draw(data, options);
                  }
                </script>
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                <script type="text/javascript">
                  google.charts.load('current', {'packages':['line']});
                  google.charts.setOnLoadCallback(drawChart);

                function drawChart() {

                  var data = new google.visualization.DataTable();
                  data.addColumn('number', 'Mês');
                  data.addColumn('number', 'Novos cadastros');
                  data.addColumn('number', 'Cadastros ativos');
                  data.addColumn('number', 'Cadastros inativos');

                  data.addRows([
                    [1,  40, 80, 41],
                    [2,  30, 69, 32],
                    [3,  25,   57, 25],
                    [4,  11, 18, 10],
                    [5,  11, 17, 10],
                    [6,   8, 13,  7],
                    [7,   7, 12,  9],
                    [8,  12, 29, 10],
                    [9,  16, 42, 14],
                    [10, 12, 30, 11],
                    [11,  5,  7,  4],
                    [12,  6,  8,  5]
                  ]);

                  var options = {
                    chart: {
                      title: 'Relatorio mensal',
                      subtitle: 'compreenção de crecimento'
                    },
                    width: 900,
                    height: 500,
                    axes: {
                      x: {
                        0: {side: 'top'}
                      }
                    }
                  };

                  var chart = new google.charts.Line(document.getElementById('line_top_x'));

                  chart.draw(data, google.charts.Line.convertOptions(options));
                }
              </script>
              </head>
              <body>
                <div id="donutchart" style="width: 900px; height: 500px;"></div>
                <div id="line_top_x"></div>
              </body>
            </html>
        </div>
    </div>
</div>
{% endblock %}